import Head from "next/head";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";
import Transaction from "../components/Transaction";

export default function Home() {
  const { isAuthenticated, user, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;

  return (
    <div className="globalStyle gradientBG">
      <Head>
        <title>Web 3.0 Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <h2 className="text-size text-center px-10">Hey Medorants!</h2>
        <p className="userText">Get rewards on medicine searches!</p>

        <Transaction />
        <button onClick={logout} className="btn-3">
          Click to logout
        </button>
      </div>
    </div>
  );
}
