import Head from "next/head";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";
import Transaction from "../components/Transaction";

export default function Home() {
  const { isAuthenticated, user, logout } = useMoralis();
  if (!isAuthenticated) return <Login />;

  return (
    <div className="bg-black bottom-3">
      <Head>
        <title>Web 3.0 Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <h2 className="">Hey There!</h2>
        <p className="">
          Your Address: <br /> <span> 🚀{user.attributes.ethAddress}</span>
        </p>

        <Transaction />
        <button onClick={logout} className="">
          Click to logout
        </button>
      </div>
    </div>
  );
}
